"""Auto-generated by ChemUnited — do not edit manually."""

from .clean import CustomProcess as cleanProcess, ProcessConfig as cleanConfig
from .MultiThreading import (
    CustomProcess as MultiThreadingProcess,
    ProcessConfig as MultiThreadingConfig,
)
from .React import CustomProcess as ReactProcess, ProcessConfig as ReactConfig
from .SimpleMultithreading import (
    CustomProcess as SimpleMultithreadingProcess,
    ProcessConfig as SimpleMultithreadingConfig,
)

PROCESSES = {
    "clean": cleanProcess,
    "MultiThreading": MultiThreadingProcess,
    "React": ReactProcess,
    "SimpleMultithreading": SimpleMultithreadingProcess,
}

CONFIGS = {
    "clean": cleanConfig,
    "MultiThreading": MultiThreadingConfig,
    "React": ReactConfig,
    "SimpleMultithreading": SimpleMultithreadingConfig,
}
